# Generated by Django 3.2 on 2021-05-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
